using UnityEngine;

/// <summary>
/// ^Μu]t参  ン廓悍З              P28.07
/// </summary> 
public class RecycleMarble : MonoBehaviour
{
    /// <summary>
    /// ^Μ杭u]计q                     p28.08
    /// </summary>
    public static int recycleMarbles;
    public static RecycleMarble instance;           // NEW

    public GameManager gm;
    public Marble mr;

    private void Awake()                            // NEW
    {
        instance = this;
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.name.Contains("u]"))   // QノI疾ㄆンㄓBz p28.06
        {
            other.gameObject.GetComponent<Rigidbody>().velocity = Vector3.zero;  // [t茁ks
            other.transform.position = new Vector3(0, 0, 5000);

            // ^Μu]计q W[
            recycleMarbles++;
            //// pG ^Μ计q 单 ┮Τu]计q ち传凹膜瑕^X  传欷U
            /////if (recycleMarbles == ControlSystem.maxMarbles) gm.SwitchTurn(false);     // p.29.08
            CheckIsRecycleAllMarbles();
            //    Debug.Log("recycleMarbles 计q: " +recycleMarbles);
        }
    }

    /// <summary>
    /// 浪dO_^Μ┮Τu]
    /// </summary>
    public void CheckIsRecycleAllMarbles()
    {
        // pG ^Μ计q 单 iog程ju]计q ち传 寄よ^X
        if (recycleMarbles == ControlSystem.shootMarbles)
        {

            gm.SwitchTurn(false);
        }
        if (GameObject.FindGameObjectsWithTag("囱LW邯ン").Length == 0)    //既
        {
            gm.allObjectDead = true;
            //gm.SwitchTurn(false);

            //mr.FlyToBottomRightnow();
            //Debug.Log("场u]莱俯供吵");
        }
    }
}
